sudo: false
language: python
dist: xenial
python:
- '3.5'
- '3.6'
- '3.7'
cache: pip
before_install:
- pip install --upgrade pip
install:
- pip install --upgrade coverage coveralls nose
- pip install python-louvain
- pip install .
script:
- nosetests --with-doctest --with-coverage --cover-package=linkpred
after_success: coveralls
deploy:
  provider: pypi
  user: rafguns
  password:
    secure: RCP8uJP9y4avKdRC1A5fkQFi00Ssgfn9gwhVpEoDVR0JkaZ+Ei9ZnseTPLbydeFxZmO1FwF7aR8ISdArjjvYxtYWmhjVLtTpkWQKvk/avT5rFNsR33eiZtzCOScJqXtrexF8IlRL4rYEKz2JA+kLnCVrfhTyx8jwdDZccC2bfH8=
  skip_existing: true
  on:
    tags: true
